services:
  - type: web
    name: fitinsure-api
    env: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
